name: 'Hello World'
pool: 
  vmImage: 'ubuntu-latest'

variables:
  - name: buildSourceVershionShort
    value: $[ format('{0}', variables.Build.SourceVersion[0]) ]
    readonly: true

stages:
- stage: VariablesOutput
  jobs:
  - job: Echo
    steps:
      - task: Bash@3
        env:
          BUILD_SOURCE_VERSION: $(buildSourceVershionShort)
        inputs:
          targetType: inline
          script: |
            echo ${BUILD_SOURCE_VERSION:0:7}
