name: 'Hello World'
pool: 
  vmImage: 'ubuntu-latest'

variables:
  - name: buildSourceVershionShort
    value: $[ format('{0}', Build.SourceVersion[0]) ]
    readonly: true

stages:
- stage: VariablesOutput
  jobs:
  - job: Echo
    steps:
    - script: |
        echo $(buildSourceVershionShort)
