name: 'Hello World'
pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: VariablesOutput
  jobs:
  - job: Echo
    steps:
      - task: Bash@3
        env:
          BUILD_SOURCE_VERSION: $Build.SourceVersion)
        inputs:
          targetType: inline
          script: |
            echo ${BUILD_SOURCE_VERSION:0:7}
