name: 'Hello World'
pool: 
  vmImage: 'ubuntu-latest'

variables:
  - name: buildSourceVershionShort
    value: ${{ format('{0}{1}', 'hello', 'world')}}
    readonly: true

stages:
- stage: 'Variables Output'
  jobs:
  - job: Echo
    steps:
    - script: echo $(buildSourceVershionShort)
